### ISSUE TITLE
 java.lang.NoSuchMethodException

### ISSUE THREAD

**Issue by TThana** [quiph/RecyclerView-FastScroller#1]
android.view.InflateException: Binary XML file line #5: Binary XML file line #5: Error inflating class com.qtalk.recyclerviewfastscroller.RecyclerViewFastScroller
    Caused by: android.view.InflateException: Binary XML file line #5: Error inflating class com.qtalk.recyclerviewfastscroller.RecyclerViewFastScroller
    Caused by: java.lang.NoSuchMethodException: <init> [class android.content.Context, interface android.util.AttributeSet]

**Comment by shahsurajk** [comment]
@TThana This looks like a proguard issue. Was `minify` set to `true` in `build.gradle`? Also, does this happen on debug variants as well?

**Comment by TThana** [comment]
thank you, it work on debug mode without proguard.

**Comment by imayank91** [comment]
I am facing the same issue. My minify is set to false for debug but it doesn't work

**Comment by RobinDeBock** [comment]
Same problem here. `Binary XML file line #10: Binary XML file line #10: Error inflating class com.qtalk.recyclerviewfastscroller.RecyclerViewFastScroller`

**Comment by shahsurajk** [comment]
What version are you using?

Regards,

Suraj Shah,
Android application developer, stackoverflow enthusiast and hobbyist coder.

**Comment by RobinDeBock** [comment]
I was following the guide from [https://androidexample365.com/a-simple-easy-to-use-and-configurable-fast-scroller-for-recyclerview/](url). That uses version 0.1.1-alpha. Thanks for answering so quick, I'll go use the new version and come back to you.

**Comment by RobinDeBock** [comment]
Using the latest version gives me this error on Gradle sync `Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.1.0-rc02] AndroidManifest.xml:24:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:8:5-25:19 to override.`

**Comment by shahsurajk** [comment]
@RobinDeBock does it work? if so, i'll contact the website guys to update the article as well.

**Comment by RobinDeBock** [comment]
Using the latest version (0.1.3) gives me this error on Gradle sync `Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91 is also present at [androidx.core:core:1.1.0-rc02] AndroidManifest.xml:24:18-86 value=(androidx.core.app.CoreComponentFactory). Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:8:5-25:19 to override.
I'm still working on trying to implement that suggestion.

**Comment by shahsurajk** [comment]
Oh, okay, seems like you're not using only AndroidX dependencies? There's a plain app support dependency present as well.

**Comment by RobinDeBock** [comment]
I guess, I don't really know what you mean. How does one fix this?

**Comment by shahsurajk** [comment]
You seem to have a problem with the dependencies, do you have [AndroidX](https://developer.android.com/jetpack/androidx/) support in the project? If not check [this](https://developer.android.com/jetpack/androidx/migrate)

**Comment by RobinDeBock** [comment]
> You seem to have a problem with the dependencies, do you have [AndroidX](https://developer.android.com/jetpack/androidx/) support in the project? If not check [this](https://developer.android.com/jetpack/androidx/migrate)

That fixed it. So I had to make use of the latest version of this library (0.1.3) and then migrate to AndroidX. Works like charm, awesome library!
