### ISSUE TITLE
Issue with handle not scrolling list in certain circumstances

### ISSUE THREAD

**Issue by joshsharp** [quiph/RecyclerView-FastScroller#14]
Hello! Thanks for making this project, I've found it really easy to integrate and style, I really appreciate that it exists :)

I have an issue where the fast scroller gets stuck sometimes. What seems to prompt it is that I scroll using the fast scroller handle, then just scroll a little by touching the `RecyclerView` directly. After this, if I grab the fast scroller handle, I can move the handle up and down all the way from the top to the bottom of the screen, but the position in the list and the popup text do not change.

I can see that my `onChange` is not getting called either. If I implement a `HandleStateListener` I can see that `onDragged` is being fired, but in this situation, it always has a position of `-1`. 

Then if I scroll the `RecyclerView` directly again, it becomes "reattached" and the fast scroller handle jumps back to the correct position and is able to be used properly again, with the correct position reported in `onDragged`, the correct text in `onChange`, and so on.

I can't work out a way to reliably replicate this — it seems to happen only sometimes, perhaps based on the position of the items on screen?

Hope this has given you enough info to be able to replicate and fix. Thanks!

**Comment by shahsurajk** [comment]
Thank you for your kind words :)

The issue you're describing looks pretty weird from the description. 

A few questions:
* Are you wrapping the view around any view which extends `NestedScrollView`? 
* Can you share a snippet of your usage of the library and the recycler view from the XML file?
* It would great if you could also share a gif of your screen recording.

**Comment by joshsharp** [comment]
It is pretty weird. There shouldn't be any `NestedScrollView`s though. Here's my layout:

```xml
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/coordinator"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity">

    <com.qtalk.recyclerviewfastscroller.RecyclerViewFastScroller
        android:id="@+id/fastscroller"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:popupDrawable="@drawable/scroller_popup"
        app:handleDrawable="@drawable/scroller_thumb"
        app:layout_constraintBottom_toBottomOf="@id/coordinator"
        app:layout_constraintTop_toBottomOf="@id/appbar"
        android:layout_marginTop="?attr/actionBarSize"
        app:handleHeight="32dp">

        <androidx.recyclerview.widget.RecyclerView
            android:id="@+id/list"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:scrollbars="none" />
    </com.qtalk.recyclerviewfastscroller.RecyclerViewFastScroller>
    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:id="@+id/status"
        app:layout_constraintBottom_toBottomOf="@id/coordinator"
        android:orientation="horizontal"
        android:background="@color/snackbar"
        android:paddingVertical="12dp"
        android:paddingHorizontal="15dp">
        <TextView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:textColor="@android:color/white"
            android:id="@+id/status_text"
            android:textSize="15sp"
            />
    </LinearLayout>
</androidx.constraintlayout.widget.ConstraintLayout>
```

There's nothing in my code that's relevant, I don't think, as I'm not programmatically attaching the scroller or anything.

I'll comment again with a gif of it happening once I'm able.

**Comment by joshsharp** [comment]
Here we go. It's a wishlist app for books. So here I scroll the `RecyclerView` to the right spot, then grab the fast scroller handle, but it isn't working. Then I scroll a little again directly on the `RecyclerView`, which fixes the fast scroller.

![20200627_175430_edited_1](https://user-images.githubusercontent.com/1171503/85917822-e5543280-b8a0-11ea-8820-6631cd4f30f1.gif)

**Comment by shahsurajk** [comment]
Very interesting. I've a few rough thoughts as to why this would be happening. Let me debug and post my results here. :)

**Comment by joshsharp** [comment]
Thanks very much!

**Comment by shahsurajk** [comment]
Hi @joshsharp thank you so much for pointing this out. I've found the issue and am working on a patch. It has something to do with view heights being enough to not include more than 2 elements on the screen at once. Patch coming soon :)

**Comment by joshsharp** [comment]
Aha, well that definitely fits my setup. Thanks very much for tracking it down!

**Comment by shahsurajk** [comment]
@joshsharp would you like to beta test the fix for me? 

If you would like to, put the aar attached to your libs folder and comment your dependency line and replace it with: 
`implementation files("${rootProject.projectDir}/libs/recyclerviewfastscroller-release.aar")` 

PFA: `recyclerviewfastscroller-release.aar.zip` remove the `.zip` extension to use it. 
 
[recyclerviewfastscroller-release.aar.zip](https://github.com/quiph/RecyclerView-FastScroller/files/4911628/recyclerviewfastscroller-release.aar.zip)

**Comment by joshsharp** [comment]
Ah great! I will give this a try when I have the time and get back to you.

**Comment by joshsharp** [comment]
Actually I have just tested it now 🙂 it does appear to fix the issue! 

However, it seems to introduce a new, different issue. The handle now appears further down the screen than where my thumb is. If you look at my previous gif, my thumb is now always roughly just above the top of the popup label, rather than the handle being directly under my thumb. Sorry!

**Comment by shahsurajk** [comment]
Didn't quite understand, could you attach a GIF on the problem you're mentioning?

**Comment by joshsharp** [comment]
![Screenshot_20200714-202313_Wishkobone](https://user-images.githubusercontent.com/1171503/87418554-37bd7f00-c615-11ea-8fa0-ad650bdc584d.png)

I've annotated this screenshot with a circle showing roughly where I'm touching the screen with my thumb. What I would expect (and what used to happen) is that the quick scroller handle sat directly under my thumb. However as I move my thumb up and down the track, the handle always sits at about this offset from where my thumb actually is. I hope that explains it.

**Comment by joshsharp** [comment]
Hmm this isn't happening now. Perhaps it was a one-off the first time I built the app to my phone? Regardless, I've been unable to replicate it since, so please don't worry about it, I think we should consider this fixed :slightly_smiling_face:
