### ISSUE TITLE
Is it possible to create a timer delay before the fast scroller pops up / is activated?

### ISSUE THREAD

**Issue by roboirc** [quiph/RecyclerView-FastScroller#20]
I am trying to find out if there is a way to control the fast scroller delay so that it shows up only after the touch event happens for X seconds? Please guide me. 
Thanks

**Comment by shahsurajk** [comment]
there's not way as of now, it's hardcoded to 200ms, but you can raise a PR and modify it.

**Comment by roboirc** [comment]
Where can I find the location of the hardcoded value in the source code?
Thanks

**Comment by shahsurajk** [comment]
you can find it here: https://github.com/quiph/RecyclerView-FastScroller/blob/master/recyclerviewfastscroller/src/main/java/com/qtalk/recyclerviewfastscroller/RecyclerViewFastScroller.kt#L128

**Comment by roboirc** [comment]
So this value controls the time delay before the fastscroller is activated / shows up correct? (200 ms) ?

**Comment by roboirc** [comment]
What files do I need to include in my project folder to be able to use your library (without importing the entire Github repository) ? 
Thanks

**Comment by shahsurajk** [comment]
You'll have to include the module `recyclerviewfastscroller`

**Comment by roboirc** [comment]
What extra lines do I need to put into the gradle files to include this module? 
I tried the methods as shown here but it still won't find the module: 

https://stackoverflow.com/questions/19299316/require-gradle-project-from-another-directory
https://stackoverflow.com/questions/47906875/how-to-add-and-use-an-external-java-source-folder-in-android-studio

Please help. Thanks.

**Comment by roboirc** [comment]
I know my questions are trivial but please do help :)

**Comment by shahsurajk** [comment]
Sorry, seems like i missed this. 

To answer your question, 
1. you have to include the code inside the folder [`recyclerviewfastscroller`](https://github.com/quiph/RecyclerView-FastScroller/tree/master/recyclerviewfastscroller) 
2.  then update your projects [`settings.gradle`](https://github.com/quiph/RecyclerView-FastScroller/blob/master/settings.gradle) to include the folder name. 
3. update your apps [`build.gradle`](https://github.com/quiph/RecyclerView-FastScroller/blob/master/sample/build.gradle#L30) to include the dependency

**Comment by roboirc** [comment]
Hi
Tried the above. Getting this error from within the recyclerviewfastscroller build gradle after importing: '
"Plugin with id 'kotlin-android' not found."
How to fix?

**Comment by shahsurajk** [comment]
I think googling it might help. At this point i won't be able to hand-hold i'm sorry. :)

**Comment by roboirc** [comment]
np thanks anyway :)

**Comment by roboirc** [comment]
I tried googling and testing it out but I was unable to do so. I see the steps on how to compile aar and include it in the project in your github. But it would be nice if you could also show us on how to just include the necessary folder and update gradle files. Much appreciated. Thanks.

**Comment by shahsurajk** [comment]
i believe #31 fixes this.

**Comment by roboirc** [comment]
So now the value can be changed? Please clarify. Thanks.

**Comment by roboirc** [comment]
Are you talking about commit 2bf12ca?

**Comment by shahsurajk** [comment]
My bad @roboirc , this issue seems unfixed for now.

**Comment by roboirc** [comment]
When will this be implemented?

**Comment by shahsurajk** [comment]
Implemented in v1.0.0

**Comment by shahsurajk** [comment]
ref: https://github.com/quiph/RecyclerView-FastScroller/releases/tag/v1.0.0

**Comment by roboirc** [comment]
What is the attribute/setting to control the pre-delay in this new version?

**Comment by roboirc** [comment]
@shahsurajk ?

**Comment by shahsurajk** [comment]
@roboirc , v1.0.0 has a `handleVisiblityDuration` XML attribute https://github.com/quiph/RecyclerView-FastScroller#customizable-xml-attributes

**Comment by shahsurajk** [comment]
if that's not what youre looking for, then you cna re-open this issue

**Comment by roboirc** [comment]
I am more eager to see you show me a working example / link to: 
https://github.com/quiph/RecyclerView-FastScroller/issues/20#issuecomment-690288126

I can't get that to work. Then I can easily modify whatever I want. Waiting for your reply. Thanks

**Comment by shahsurajk** [comment]
You can check out the sample code in this repo itself by cloning the project:

the sample application here https://github.com/quiph/RecyclerView-FastScroller/tree/master/sample is exactly what youre looking for. Can simply clone this repo and compile the app on you device. The sample app links locally to the library code
