### ISSUE TITLE
java.lang.IllegalAccessException: Should implement the OnPopupTextUpdate or OnPopupViewUpdate interface

### ISSUE THREAD

**Issue by tom5079** [quiph/RecyclerView-FastScroller#27]
Why does it raise an exception?
Just not showing the popup when it's not implemented makes much more sense

**Comment by shahsurajk** [comment]
@tom5079 let's make a point to reference issues in commit messages like "Fixes #27", this way, whenever the commit is merged to master, github closes the issue with the reference commit.
