### ISSUE TITLE
Orientation Support? 

### ISSUE THREAD

**Issue by rgocal** [quiph/RecyclerView-FastScroller#3]
Does this fastscroller support Horizontal and Vertical Recyclerviews?

**Comment by shahsurajk** [comment]
As you can see the [todo](https://github.com/quiph/RecyclerView-FastScroller#todo), it's not yet planned, but it's definitely going to be implemented someday. For now it only supports vertical recyclerviews.

**Comment by rgocal** [comment]
Alright, thank you for the reply. Im looking for a fastscroll for a launcher app drawer that supports orientation.

**Comment by gilgoldzweig** [comment]
Is there a reason for not appending it as part of the LayoutManager? 

That seems like a better way to add support for basically any direction

**Comment by shahsurajk** [comment]
Interesting, it didn't hit me. But could you elaborate your solution, as in what would you do? 
Are you hinting `layoutManager.orientation = RecyclerView.HORIZONTAL`? cause i think we can totally do that!

**Comment by gilgoldzweig** [comment]
Yeah, something in that realm.

**Comment by shahsurajk** [comment]
Yeah, we can do this, just need to figure out a bit of math, so currently there is an attribute to do this, `fastScrollDirection` this will simply be deprecated and the fastscroller will internally use the orientation provided in the `LayoutManager` but we still have to port the code to make it work in the horizontal direction.

**Comment by shahsurajk** [comment]
@tom5079 you'll have to also add "Fixes #3" in your last commit message for #29

**Comment by shahsurajk** [comment]
@tom5079 , it didn't close this issue, manually closing it. 

fixed with: https://github.com/quiph/RecyclerView-FastScroller/releases/tag/v1.0.0

**Comment by tom5079** [comment]
@shahsurajk ok to be honest I'm confused by it now
