### ISSUE TITLE
[Bug] FastScroll handle disappears

### ISSUE THREAD

**Issue by shahsurajk** [quiph/RecyclerView-FastScroller#33]
## Bug Description 
When you scroll to the last element and re-draw the fragment, the handle disappears (it's actually below the visible screen length). 

Recording for reference :
![output](https://user-images.githubusercontent.com/12149313/93027245-4d592000-f629-11ea-9d7b-9080a19d1342.gif)

**Comment by shahsurajk** [comment]
@tom5079 do you wish to try this out?

**Comment by tom5079** [comment]
@shahsurajk I'll try it for sure. ~Can you provide me a reproducible code?~ Found it.

**Comment by tom5079** [comment]
@shahsurajk Is there any slack channel that we can work on together?

**Comment by tom5079** [comment]
@shahsurajk actually, #29 fixes it

**Comment by shahsurajk** [comment]
@tom5079 can you amend your last commit on #29 and add the commit message "Fixes #33"

**Comment by shahsurajk** [comment]
fixed with https://github.com/quiph/RecyclerView-FastScroller/releases/tag/v1.0.0
