### ISSUE TITLE
[Sample] Sample fragment to test horizontal scroll

### ISSUE THREAD

**Issue by shahsurajk** [quiph/RecyclerView-FastScroller#34]
Should create a sample fragment to test horizontal scroll and use it inside the view pager. Was thinking of programming languages Alphabetically sorted. 

Horizontal scroll is yet to be merged. It's currently present as a PR and can be tracked at #29

**Comment by nsalazar0429** [comment]
I would like to work on this issue once available

**Comment by shahsurajk** [comment]
@cfsnsalazar thank you for your interest, though i think @tom5079 was working on this.

**Comment by shahsurajk** [comment]
@cfsnsalazar you can start working on this by forking the project and checking out the `development` branch

**Comment by nsalazar0429** [comment]
@shahsurajk For sure . Sorry for not starting this yet , I have been busy these last few days with other obligations. I will be starting ASAP

**Comment by shahsurajk** [comment]
@cfsnsalazar no worries. I shall assign this to you then. Feel free to ask questions here. :)

**Comment by nsalazar0429** [comment]
I won't be working on this issue anymore. I currently don't have time

**Comment by tom5079** [comment]
@cfsnsalazar literally took 30 minutes

**Comment by shahsurajk** [comment]
fixed with https://github.com/quiph/RecyclerView-FastScroller/releases/tag/v1.0.0
