### ISSUE TITLE
[Bug] Handle is moved when touched after sibling view stub is inflated

### ISSUE THREAD

**Issue by vokilam** [quiph/RecyclerView-FastScroller#38]
### Setup
I have a vertical linear layout with a `RecyclerView` and a banner ViewStub above it.

```xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <ViewStub
        android:id="@+id/stub"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout="@layout/list_item"/>

    <com.qtalk.recyclerviewfastscroller.RecyclerViewFastScroller
        android:id="@+id/fastScroller"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1"
        app:handleHeight="40dp"
        app:handleWidth="40dp"
        app:handleHasFixedSize="true">

        <androidx.recyclerview.widget.RecyclerView
            android:id="@+id/recycler"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:layoutManager="androidx.recyclerview.widget.LinearLayoutManager"
            />
    </com.qtalk.recyclerviewfastscroller.RecyclerViewFastScroller>
    
</LinearLayout>
```
Banner view stub is inflated later, after some conditions are met. To simplify this:
```kotlin
class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        findViewById<RecyclerView>(R.id.recycler).run {
            adapter = MyListAdapter().also { it.submitList((0..100).toList()) }
        }

        Handler().postDelayed({
            findViewById<ViewStub>(R.id.stub).inflate()
        }, 500)
    }
}
```
### Behavior
**Actual** 
After view stub is inflated, handle is moved down when touched (approximately by an inflated view height). List is also scrolled down. Touch position does not correspond to a handle position.

![device-2020-09-29-210938](https://user-images.githubusercontent.com/683849/94599227-d3679e80-0298-11eb-9563-50e7ec88363f.gif)

**Expected**
Handle is not moved when touched. Handle is moved _under_ a finger.

Here is the project that reproduces this issue: [testfastscroll.zip](https://github.com/quiph/RecyclerView-FastScroller/files/5301062/testfastscroll.zip)

Can you suggest any workarounds?

**Comment by shahsurajk** [comment]
@vokilam what version are you on?

**Comment by vokilam** [comment]
recyclerviewfastscroller:0.2.3

**Comment by tom5079** [comment]
#29 Fixes it

**Comment by vokilam** [comment]
Same incorrect behavior is reproduced in fullscreen mode – handle is moved down when touched (approximately by status bar height)

```kotlin
override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        window.setFlags(
            WindowManager.LayoutParams.FLAG_FULLSCREEN,
            WindowManager.LayoutParams.FLAG_FULLSCREEN
        )

        setContentView(R.layout.activity_main)
        ...
}
```

**Comment by shahsurajk** [comment]
fixed with https://github.com/quiph/RecyclerView-FastScroller/releases/tag/v1.0.0

@vokilam can you check this issue on the latest release?

**Comment by vokilam** [comment]
Initial issue is fixed. Issue mentioned in https://github.com/quiph/RecyclerView-FastScroller/issues/38#issuecomment-701258330 is still reproducible

**Comment by shahsurajk** [comment]
@vokilam , can you create a new issue with the details mentioned so it becomes easier to track. i'll close this one.
