### ISSUE TITLE
Plugin with id 'com.android.application' not found.

### ISSUE THREAD

**Issue by nyxee** [quiph/RecyclerView-FastScroller#42]
I get that error when i try to load the sample project in Android Studio.

**Comment by shahsurajk** [comment]
i don't think this issue is due to the library. you can try removing the lib dependency and re-trying to see if this issue goes away or not.

**Comment by nyxee** [comment]
yes. the library is ok.the problem is with the sample project. I have tried to make it work but i have failed only due to the kotlinx-serialization plugin.

**Comment by shahsurajk** [comment]
not sure. maybe you can try searching stackoverflow for possible solutions. closing this issue cause it doesnt belong here.
