### ISSUE TITLE
FastScroll Padding?

### ISSUE THREAD

**Issue by MrZ3T4** [quiph/RecyclerView-FastScroller#5]
Is there a way to set an upper and lower margin without affecting the recyclerview?

Since at the end of the scroll it is not possible to reach the last item and it must slide out of view :/

**Comment by shahsurajk** [comment]
No, not yet. This could be a good first issue for people to work on.

**Comment by dhruvnagarajan** [comment]
@MrZ3T4 Won't clipToPadding solve this issue?

**Comment by shahsurajk** [comment]
@dhruvnagarajan i'm not sure how it would help, do you have an implementation in mind?

**Comment by dhruvnagarajan** [comment]
> Since at the end of the scroll it is not possible to reach the last item and it must slide out of view :/

This is not entirely clear.

It appears that @MrZ3T4 is having an overlap of views towards the bottom of the list, so I recommended use of padding for the last item.

**Comment by shahsurajk** [comment]
@tom5079 Let's amend the commit message for #30 with "Fixes #5"

**Comment by tom5079** [comment]
@shahsurajk I said i'll reopen that issue after #29 is merged. Pull requests after #30 is an entangled mess, so I need to cherrypick commits

**Comment by shahsurajk** [comment]
got it, what i meant @tom5079 is let's amend the commit message with a "fixes .. " message, like something mentioned here: https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue. so, this will auto close the issue once the commit is merged to master.

**Comment by tom5079** [comment]
uh... "resolves" does the same thing too...

**Comment by shahsurajk** [comment]
@tom5079 , yes, resolves works too, but you'll have to write that in the commit message. :)

**Comment by tom5079** [comment]
it doesn't have to be in the commit message, it works when it's on the PR comment. check this out
![image](https://user-images.githubusercontent.com/7948651/93661991-47cf6000-fa97-11ea-8327-49dade7c5984.png)

**Comment by shahsurajk** [comment]
it does, though i'm not sure if it will auto-close the issue once the PR is merged. will it?

**Comment by tom5079** [comment]
I guess it will, but not 100% sure. wanna test it?

**Comment by tom5079** [comment]
@shahsurajk Turns out that it does close the issue. check https://github.com/tom5079/PR
keep in mind that it only closes the issue when the PR is merged to `master` branch

**Comment by shahsurajk** [comment]
@tom5079 , yes. got to know of it now as well: https://stackoverflow.com/a/15827689/4820556. Though it used to be based only on commit messages early on.  My bad here. :beer:

**Comment by tom5079** [comment]
all good 😄

**Comment by shahsurajk** [comment]
fixed with https://github.com/quiph/RecyclerView-FastScroller/releases/tag/v1.0.0
