### ISSUE TITLE
If recyclerView in SwipeRefreshLayout, drag the fast scroll handler will cause swipeRefreshLayout to start refreshing

### ISSUE THREAD

**Issue by westlinkin** [quiph/RecyclerView-FastScroller#6]

**Comment by shahsurajk** [comment]
Interesting. Do you have a gif or a screen record of the same?

**Comment by westlinkin** [comment]
Used another library, closed.

**Comment by shahsurajk** [comment]
Would you post a link to the library you ended up using, might be helpful if someone else stumbles upon this.

**Comment by westlinkin** [comment]
related issue in other lib: https://github.com/L4Digital/FastScroll/issues/30
