### ISSUE TITLE
How to wrap an exist RecyclerView such as in PreferenceFragmentCompat?

### ISSUE THREAD

**Issue by imknown** [quiph/RecyclerView-FastScroller#7]
See here: https://github.com/quiph/RecyclerView-FastScroller/issues/7#issuecomment-554820953

**Comment by shahsurajk** [comment]
Interesting. Does it extend a recycler view? If not then i think a similar implementation will have to be written for other components

**Comment by imknown** [comment]
Hi, @shahsurajk, It looks like these below:

``` java
package androidx.preference;

public abstract class PreferenceFragmentCompat extends Fragment implements ... {
    private static final String TAG = "PreferenceFragment";

    @SuppressWarnings("WeakerAccess") /* synthetic access */
    RecyclerView mList;

    public final RecyclerView getListView() {
        return mList;
    }

    ...
}
```

``` kotlin
class SettingsFragment : PreferenceFragmentCompat() {
    val recyclerView: RecyclerView = listView
}
```

**Comment by shahsurajk** [comment]
Interesting, maybe we could attach the `RecycerView` directly. Definitely looks like a good feature to work on. Thanks for reporting, Would be great if you could post a sample of what you're trying to build, would help us bootstrapping things to build for this component.

**Comment by imknown** [comment]
@shahsurajk Thanks for your reply 😄,
It's my mistake, I read the document hastily before.
Now I find the `attachFastScrollerToRecyclerView(recyclerView)` as you mentioned can solve this.
Thanks again~
